### PR TITLE
Allow disabling ingress controller

### PR DESCRIPTION
**Pull request by ashleydavies**
We've been using this chart with an `nginx-ingress` controller we already set up, but realised this was still deploying its own `ingress-nginx` controller.

I believe this change will allow the disabling of the ingress controller without any default behaviour change, based on the docs:

https://helm.sh/docs/topics/charts/
> The condition field holds one or more YAML paths (delimited by commas). If this path exists in the top parent's values and resolves to a boolean value, the chart will be enabled or disabled based on that boolean value. Only the first valid path found in the list is evaluated and if no paths exist then the condition has no effect.

Since there is no default for `ingress.controller.enabled`, by default this should fall back to `ingress.enabled` which is the current existing behaviour.

### CODE REVIEW

**Comment by ashleydavies** [comment]
Just going to test this properly before being confident this can be landed

**Comment by siggisim** [comment]
Seems fine to me - the use cases here is for the chart to handle creating the ingress objects, but not deploy the nginx subchart (because it's already deployed)?

Could you bump the Chart.yaml version as well?

**Comment by ashleydavies** [comment]
Pretty much, yep -- we overrode `ingress.service` so we're using our own ingress handler, and then realised this was still deploying the controller (my fault, didn't notice this in my last changeset)

Thanks again for being accommodating of changes! Will bump that value now

**Comment by siggisim** [comment]
Looks good, thanks!

**Pull request merged**
